const $=s=>document.querySelector(s);let state=null,running=false,paused=false,presentationMode=false;
async function api(path,opts={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...opts});if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function short(s,n=14){if(!s)return'—';return s.length>n?s.slice(0,n)+'…':s}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2400)}
function render(s){state=s;$('#mode').textContent=s.mode;$('#campaignId').textContent=s.campaign_id;$('#lastAction').textContent=s.last_action;const externalMode=s.step===0&&(s.events?.length||0)>0;const p=externalMode?100:Math.round(s.step/s.total_steps*100);$('#stepText').textContent=externalMode?`API LAB · ${s.events.length} eventos`:`${s.step} / ${s.total_steps} eventos`;$('#progressPct').textContent=externalMode?'API':p+'%';$('#progressBar').style.width=p+'%';$('#riskValue').textContent=s.risk;const rl=s.risk>=80?'CRÍTICO':s.risk>=60?'ALTO':s.risk>=30?'ELEVADO':'NORMAL';$('#riskLabel').textContent=rl;$('#riskLabel').style.color=s.risk>=60?'var(--red)':s.risk>=30?'var(--amber)':'var(--green)';$('#signalCount').textContent=s.signals.length;$('#incidentState').textContent=s.incident?s.incident.state:'NÃO ABERTO';$('#incidentId').textContent=s.incident?s.incident.incident_id:'aguardando correlação';$('#upstreamHits').textContent=s.upstream_hits;$('#integrityState').textContent=s.verification.overall;$('#tamperState').textContent=s.tamper_status;$('#offlineState').textContent=s.offline_verify;renderIncident(s);renderPath(s);renderEvents(s);renderGraph(s);renderPolicy(s);renderIntegrity(s);renderSourceHealth(s);renderWhy(s);renderDecisionPipeline(s);renderQualification(s);syncTimeMachine(s)}
function renderIncident(s){const i=s.incident,b=$('#incidentBadge');b.className='badge '+(i?'open':'neutral');b.textContent=i?'OPEN / HIGH':'CANDIDATE';$('#incidentSeverity').textContent=i?'Incidente correlacionado':'Sem incidente';$('#incidentSummary').textContent=i?i.summary:'Aguardando sinais suficientes.';$('#principal').textContent=i?i.principal:'—';$('#incidentStatus').textContent=i?i.state:'—';$('#incidentRisk').textContent=i?i.risk_score:s.risk;$('#policyTags').textContent=i?i.policy_tags.join(' · '):'—'}
function renderPath(s){const e=$('#attackPath');if(!s.events.length){e.innerHTML='<div class="empty" style="grid-column:1/-1">A campanha ainda não começou.</div>';return}e.innerHTML=s.events.slice(-12).map(x=>`<div class="attack-node ${x.severity.toLowerCase()} ${x.phase==='FASE 2'?'phase2node':''}"><div class="n-source">${esc(x.source)} · LSN ${x.lsn}</div><div class="n-title">${esc(x.summary)}</div><div class="n-meta">${esc(x.actor)} → ${esc(short(x.asset,24))}</div></div>`).join('')}
function renderEvents(s){const b=$('#eventRows');if(!s.events.length){b.innerHTML='<tr><td colspan="5" class="empty">Nenhum evento processado.</td></tr>';return}b.innerHTML=[...s.events].reverse().map(e=>`<tr><td>${e.lsn}</td><td><span class="evt-title">${esc(e.source)}</span><span class="evt-sub">${esc(e.phase)}</span></td><td><span class="evt-title">${esc(e.event_type)}</span><span class="evt-sub">${esc(e.summary)}</span></td><td><span class="evt-title">${esc(e.actor)}</span><span class="evt-sub">${esc(e.asset)}</span></td><td><span class="outcome ${esc(e.outcome)}">${esc(e.outcome)}</span><span class="evt-sub">${esc(e.reason_code||'')}</span></td></tr>`).join('')}
function renderGraph(s){const e=$('#graph'),nodes=s.graph.nodes||[],edges=s.graph.edges||[];$('#graphStats').textContent=`${nodes.length} nós / ${edges.length} arestas`;if(!nodes.length){e.innerHTML='<div class="empty graph-empty">O grafo surgirá conforme os sinais forem correlacionados.</div>';return}const W=620,H=355,v=nodes.slice(-24),ids=new Set(v.map(n=>n.id)),pos=new Map();v.forEach(n=>{const ring=n.kind==='incident'?0:n.kind==='event'?1:2,a=v.filter(x=>(x.kind==='incident'?0:x.kind==='event'?1:2)===ring),k=a.indexOf(n),r=ring===0?0:ring===1?95:145,ang=Math.PI*2*(k/Math.max(a.length,1))-Math.PI/2;pos.set(n.id,{x:W/2+Math.cos(ang)*r,y:H/2+Math.sin(ang)*r})});const lines=edges.filter(x=>ids.has(x.from)&&ids.has(x.to)).map(x=>{const a=pos.get(x.from),b=pos.get(x.to);return`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" class="graph-line"/>`}).join(''),colors={incident:'#ff5b66',event:'#43a5ff',actor:'#45d9d0',asset:'#a78bfa'},circles=v.map(n=>{const p=pos.get(n.id),r=n.kind==='incident'?20:n.kind==='event'?8:10;return`<g class="graph-node"><circle cx="${p.x}" cy="${p.y}" r="${r}" fill="${colors[n.kind]||'#6d87a1'}" stroke="#d7e9f9"/><text x="${p.x}" y="${p.y+r+13}" text-anchor="middle">${esc(short(n.label,18))}</text></g>`}).join('');e.innerHTML=`<svg viewBox="0 0 ${W} ${H}">${lines}${circles}</svg>`}
function renderPolicy(s){$('#compromisedCheck').textContent=s.incident?'SIM':'NÃO';$('#compromisedCheck').style.color=s.incident?'var(--red)':'var(--green)';const a=s.pending_approval,b=$('#approvalBox');b.innerHTML=a?`<span>HITL / ${esc(a.state)}</span><b>${esc(a.approval_id)} — ${esc(a.tool)}</b><small>${esc(a.principal)} → ${esc(a.target)} · single-use=${a.single_use}</small>`:'<span>HITL</span><b>Nenhuma aprovação pendente</b><small>Ações críticas podem exigir decisão humana.</small>'}
function renderIntegrity(s){$('#lastLsn').textContent=s.events.length?s.events.at(-1).lsn:0;$('#eventCount').textContent=s.events.length;$('#merkleRoot').textContent=s.merkle_root;$('#packageRoot').textContent=s.package_root||'—';$('#merkleShort').textContent='Merkle: '+short(s.merkle_root,18);$('#merkleState').textContent=s.verification.merkle;$('#chainVerify').textContent=s.verification.chain;$('#merkleVerify').textContent=s.verification.merkle;$('#manifestVerify').textContent=s.verification.manifest||'NOT RUN';$('#packageVerify').textContent=s.verification.package_root||'NOT RUN'}
function renderQualification(s){$('#qualification').innerHTML=s.qualification.map(x=>`<div class="qitem"><span>${esc(x.id)}</span><b><em>esperado ${esc(x.expected)}</em><strong class="${x.ok?'ok':'pending'}">${x.ok?esc(x.observed):'PENDING'}</strong></b></div>`).join('');const all=s.qualification.every(x=>x.ok),b=$('#qualificationBadge');b.textContent=all?'POC QUALIFIED':'EM EXECUÇÃO';b.style.color=all?'var(--green)':''}


function renderDecisionPipeline(s){const sig=s.signals||[],corr=s.incident?.correlation||null,pol=(s.events||[]).filter(e=>e.details?.policy_decision);const badge=$('#pipelineBadge');badge.textContent=pol.length?'END-TO-END':corr?'CORRELATED':sig.length?'DETECTING':'AGUARDANDO';badge.style.color=pol.length?'var(--green)':corr?'var(--cyan)':'';$('#detectionRules').innerHTML=sig.length?[...sig].reverse().map(x=>`<div class="decision-row"><div class="top"><b>${esc(x.rule_id||x.reason_code)}</b><strong class="${esc(x.severity)}">${esc(x.severity)} · +${esc(x.score??'')}</strong></div><small>LSN ${x.lsn} · ${esc(x.source_class||x.source)} · ${esc(x.rule_explanation||x.reason_code)}</small></div>`).join(''):'<div class="empty">Nenhuma regra disparada.</div>';if(corr){$('#correlationDecision').innerHTML=`<div class="correlation-card"><div class="score"><div><span>correlation score</span><b>${esc(corr.score)}</b></div><strong class="${corr.qualifies?'ok':'pending'}">${corr.qualifies?'QUALIFIED':'CANDIDATE'}</strong></div><div class="correlation-tags">${(corr.sources||[]).map(x=>`<span>${esc(x)}</span>`).join('')}</div><p>${(corr.signal_ids||[]).length} sinais · ${(corr.entities||[]).length} entidades · confidence=${esc(corr.confidence)} · data-plane=${corr.has_data_plane_evidence?'sim':'ainda não'}</p></div>`}else{$('#correlationDecision').innerHTML='<div class="empty">Sem componente qualificado.</div>'}$('#policyDecisions').innerHTML=pol.length?[...pol].reverse().map(e=>{const d=e.details.policy_decision;return`<div class="decision-row"><div class="top"><b>${esc(d.reason_code)}</b><strong class="${esc(e.outcome)}">${esc(e.outcome)}</strong></div><small>LSN ${e.lsn} · ${esc(e.event_type)} · effect_allowed=${d.effect_allowed} · ${esc(d.explanation)}</small></div>`}).join(''):'<div class="empty">Nenhuma decisão de policy.</div>'}
function renderSourceHealth(s){const rows=s.source_health||[],active=rows.filter(x=>x.status==='ACTIVE').length;$('#sourceCountBadge').textContent=active+' ativas';$('#sourceHealth').innerHTML=rows.map(x=>`<div class="source-item"><b><span>${esc(x.source)}</span><strong class="${x.status}">${x.status}</strong></b><span>${x.events} eventos · ${esc((x.matched||[]).join(', ')||'aguardando')}</span></div>`).join('')}
function renderWhy(s){const w=s.why_incident||{status:'NOT_OPEN',reasons:[]};$('#whyBadge').textContent=w.status==='OPEN'?'EXPLICADO':'AGUARDANDO';$('#whyBadge').style.color=w.status==='OPEN'?'var(--green)':'';$('#whySummary').textContent=w.summary||'Aguardando sinais.';$('#whyList').innerHTML=(w.reasons||[]).slice().reverse().map(x=>`<div class="why-item"><span class="why-lsn">LSN ${x.lsn}</span><div><b>${esc(x.reason_code)} · ${esc(x.source)}</b><small>${esc(x.summary)} · ${esc(x.actor)} → ${esc(short(x.asset,26))}</small></div></div>`).join('')||'<div class="empty">Sem cadeia causal disponível.</div>'}
function syncTimeMachine(s){const slider=$('#asofSlider');slider.max=Math.max(s.total_steps,s.events.length);if(!slider.dataset.touched){slider.value=s.step;renderAsofLocal(s)}}
function renderAsofLocal(s){$('#asofLabel').textContent='LSN '+s.step;$('#asofRisk').textContent=s.risk;$('#asofIncident').textContent=s.incident?'OPEN':'NÃO';$('#asofUpstream').textContent=s.upstream_hits;$('#asofApproval').textContent=s.pending_approval?.state||'NONE';$('#asofNarrative').textContent=s.step?'Estado atual da campanha. Arraste para voltar no histórico.':'Antes do primeiro evento.'}
async function renderAsof(lsn){try{const a=await api('/api/asof?lsn='+encodeURIComponent(lsn));$('#asofLabel').textContent='LSN '+a.as_of_lsn;$('#asofRisk').textContent=a.risk;$('#asofIncident').textContent=a.incident?'OPEN':'NÃO';$('#asofUpstream').textContent=a.upstream_hits;$('#asofApproval').textContent=a.approval_state;const last=a.events?.at(-1);$('#asofNarrative').textContent=last?`${last.phase} · ${last.source}: ${last.summary}`:'Antes do primeiro evento.'}catch(e){toast('AS-OF falhou: '+e.message)}}
async function inspectEvidence(lsn){try{const r=await api('/api/evidence/object?lsn='+encodeURIComponent(lsn));const raw=r.event?.details?.raw_telemetry,norm=r.event?.details?.normalized_telemetry;$('#evidenceMeta').innerHTML=`<div>LSN <b>${r.event.lsn}</b> · ${esc(r.event.source)} · chain_link_valid=<b style="color:${r.provenance.chain_link_valid?'var(--green)':'var(--red)'}">${r.provenance.chain_link_valid}</b></div>${raw||norm?`<div class="raw-canonical"><div><b>RAW TELEMETRY</b><pre>${esc(JSON.stringify(raw||{},null,2))}</pre></div><div><b>CANONICAL EVENT</b><pre>${esc(JSON.stringify(norm||{},null,2))}</pre></div></div>`:''}`;$('#evidenceJson').textContent=JSON.stringify(r,null,2)}catch(e){$('#evidenceMeta').textContent='Evidência não encontrada';$('#evidenceJson').textContent='{}'}}
async function loadReport(){try{const r=await api('/api/report');$('#reportSummary').textContent=r.executive_summary;$('#reportControls').innerHTML=Object.entries(r.controls||{}).map(([k,v])=>`<div class="report-control"><span>${esc(k.replaceAll('_',' '))}</span><b>${esc(v)}</b></div>`).join('');$('#reportLimitations').innerHTML=(r.limitations||[]).map(x=>`<li>${esc(x)}</li>`).join('')}catch(e){toast('Relatório falhou: '+e.message)}}

async function loadCompare(){try{const from=Number($('#compareFrom').value||0),to=Number($('#compareTo').value||0),r=await api('/api/compare?from='+encodeURIComponent(from)+'&to='+encodeURIComponent(to));$('#compareSummary').textContent=`LSN ${r.from.as_of_lsn} → ${r.to.as_of_lsn}: risco ${r.from.risk} → ${r.to.risk}, incidente ${r.delta.incident}.`;const labels={events:'Eventos',risk:'Risco',upstream_hits:'Upstream hits',incident:'Incidente',approval:'Approval',tamper:'Tamper',case_effect:'Efeito no caso'};$('#compareGrid').innerHTML=Object.entries(r.delta).map(([k,v])=>`<div class="compare-item"><span>${esc(labels[k]||k)}</span><b class="${typeof v==='number'&&v>0?'delta-positive':''}">${esc(v)}</b></div>`).join('')}catch(e){toast('Comparação falhou: '+e.message)}}
async function loadIntegration(){try{const r=await api('/api/heraclitus-adapter');$('#integrationStatus').textContent=r.status;$('#integrationStatus').style.color=r.status==='CONNECTED'?'var(--green)':'var(--amber)';if(r.status!=='CONNECTED'){ $('#integrationNote').textContent=r.note||r.error||'HeraclitusDB local não configurado.';$('#integrationSurfaces').innerHTML='';return }$('#integrationNote').textContent='Adapter read-only conectado a um HeraclitusDB em loopback. O dashboard continua sem privilégios de escrita.';const surfaces=r.snapshot?.surfaces||{};$('#integrationSurfaces').innerHTML=Object.entries(surfaces).map(([k,v])=>`<div class="integration-surface"><span>${esc(k)}</span><b class="${esc(v.status)}">${esc(v.status)}</b></div>`).join('')}catch(e){$('#integrationStatus').textContent='UNAVAILABLE';$('#integrationNote').textContent=e.message}}

function labLog(label,r){const d=r?.decision,e=r?.event;$('#apiLabLog').innerHTML=`<b>${esc(label)}</b> · ${esc(d?.outcome||r?.status||e?.outcome||'PASS')} · ${esc(d?.reason_code||e?.reason_code||'')} · upstream=${esc(e?.upstream_delta??r?.upstream_hits??'n/a')}`}
async function apiLabPhase1(){if((state?.events?.length||0)>0){toast('Reinicie o ambiente antes de iniciar o API Lab');return}const samples=[
 ['firewall',{event_id:'RAW-FW-001',src_ip:'203.0.113.42',dst_service:'portal-synthetic',action:'OBSERVED',severity:'MEDIUM',waf_score:71}],
 ['identity',{event_id:'RAW-IAM-002',principal:'service-account-17',source_ip:'203.0.113.42',context:'new-device',result:'OBSERVED',severity:'HIGH',mfa:'not-applicable',device_trust:'unknown'}],
 ['host',{event_id:'RAW-HOST-003',principal:'service-account-17',host:'srv-app-07',process:'synthetic-worker',os:'Linux',severity:'HIGH',parent:'app-service'}],
 ['network',{event_id:'RAW-NET-004',principal:'service-account-17',src_host:'srv-app-07',dst_host:'srv-db-02',dst_port:5432,severity:'HIGH'}],
 ['db',{event_id:'RAW-DB-005',principal:'service-account-17',database:'db-judicial-lab',operation:'query',object:'synthetic_case_metadata',rows:47,severity:'HIGH'}],
 ['app',{event_id:'RAW-APP-006',principal:'service-account-17',resource:'case://SYNTHETIC/RE-000001',action:'resource_access',classification:'RESTRICTED',severity:'CRITICAL'}]
];for(const [kind,raw] of samples){const r=await api('/api/telemetry?kind='+kind,{method:'POST',body:JSON.stringify(raw)});render(r.state);$('#apiLabLog').innerHTML=`<b>INGEST</b> · ${esc(kind)} · detection=${esc(r.detection?.rule_id||'NONE')} · LSN ${r.ingested.lsn}`;await new Promise(x=>setTimeout(x,180))}toast('Fase 1 ingerida via APIs locais')}
const exportBody=()=>({action:'export_restricted',principal:'service-account-17',target:'document://SYNTHETIC/DOC-001',parameters:{document:'DOC-001',format:'pdf'}});
async function apiLabWrite(){const r=await api('/api/action',{method:'POST',body:JSON.stringify({action:'case_write',principal:'service-account-17',target:'case://SYNTHETIC/RE-000001',parameters:{field:'metadata'}})});render(r.state);labLog('WRITE',r)}
async function apiLabExport(label='EXPORT'){const r=await api('/api/action',{method:'POST',body:JSON.stringify(exportBody())});render(r.state);labLog(label,r);return r}
async function apiLabApprove(){const id=state?.pending_approval?.approval_id;if(!id){toast('Nenhuma approval PENDING');return}const r=await api('/api/approval/grant',{method:'POST',body:JSON.stringify({approval_id:id,approver:'human:approver-dashboard'})});render(r.state);labLog('HITL',r)}
async function refresh(){try{render(await api('/api/state'))}catch(e){toast('Falha ao ler estado: '+e.message)}}
$('#resetBtn').onclick=async()=>{running=false;paused=false;$('#pauseBtn').textContent='Pausar';render(await api('/api/reset',{method:'POST'}));toast('Ambiente reiniciado')};$('#stepBtn').onclick=async()=>render(await api('/api/step',{method:'POST'}));$('#pauseBtn').onclick=()=>{paused=!paused;$('#pauseBtn').textContent=paused?'Continuar':'Pausar';toast(paused?'Campanha pausada':'Campanha retomada')};$('#presentationBtn').onclick=()=>{presentationMode=!presentationMode;$('#presentationBtn').textContent='Modo apresentação: '+(presentationMode?'ON':'OFF');if(presentationMode)$('#runSpeed').value='900';toast(presentationMode?'Checkpoints narrativos ativados':'Modo apresentação desativado')};$('#runBtn').onclick=async()=>{if(running)return;running=true;paused=false;$('#pauseBtn').textContent='Pausar';$('#runBtn').textContent='Executando…';const checkpoints={5:'Incidente aberto: explique a correlação multi-fonte.',7:'Fim da Fase 1: mostre o principal comprometido e a ponte para policy.',11:'HITL: uma ação autorizada chegou exatamente uma vez ao upstream.',15:'Tamper detectado: mostre HRKL, hash-chain e Merkle.'};try{while(running&&state&&!state.completed){if(paused){await new Promise(r=>setTimeout(r,120));continue}render(await api('/api/step',{method:'POST'}));if(presentationMode&&checkpoints[state.step]){paused=true;$('#pauseBtn').textContent='Continuar';toast(checkpoints[state.step])}await new Promise(r=>setTimeout(r,Number($('#runSpeed').value||500)))}if(state?.completed)toast('Campanha completa executada')}finally{running=false;$('#runBtn').textContent='Executar campanha'}};
$('#tamperBtn').onclick=async()=>{const kind=$('#tamperKind').value;const r=await api('/api/tamper-demo?kind='+encodeURIComponent(kind),{method:'POST'});$('#tamperResult').innerHTML=`${esc(kind)}: <b style="color:${r.status==='DETECTED'?'var(--red)':'var(--green)'}">${esc(r.status)}</b> · chain=${esc(r.verification?.chain||'—')} · merkle=${esc(r.verification?.merkle||'—')}`;toast('Sabotagem '+kind+' executada')};$('#exportBtn').onclick=async()=>{const r=await api('/api/export',{method:'POST'});$('#exportResult').innerHTML=`<b style="color:var(--green)">${r.status}</b> · ${esc(r.path)} · sha256 ${esc(short(r.sha256,20))}`;toast('Evidence Bundle gerado')};$('#downloadBtn').onclick=()=>{location.href='/api/evidence/download'};$('#loadEvidenceBtn').onclick=()=>inspectEvidence(Number($('#evidenceLsn').value||1));$('#reportBtn').onclick=loadReport;$('#asofSlider').oninput=e=>{e.currentTarget.dataset.touched='1';renderAsof(Number(e.currentTarget.value))};$('#compareBtn').onclick=loadCompare;$('#integrationBtn').onclick=loadIntegration;$('#downloadReportBtn').onclick=()=>{location.href='/api/report/download'};$('#apiPhase1Btn').onclick=apiLabPhase1;$('#apiWriteBtn').onclick=apiLabWrite;$('#apiExportBtn').onclick=()=>apiLabExport('REQUEST EXPORT');$('#apiApproveBtn').onclick=apiLabApprove;$('#apiExecuteBtn').onclick=()=>apiLabExport('EXECUTE EXPORT');$('#apiReplayBtn').onclick=()=>apiLabExport('REPLAY');$('#faultBtn').onclick=async()=>{const kind=$('#faultKind').value;try{const r=await api('/api/fault-demo?kind='+encodeURIComponent(kind),{method:'POST'});$('#faultResult').innerHTML=`<div class="fault-flow"><div class="fault-state"><span>estado inicial</span><b>${esc(r.initial_state||r.decision||'—')}</b></div><div class="fault-arrow">→</div><div class="fault-state"><span>estado final</span><b style="color:${r.status==='PASS'?'var(--green)':'var(--red)'}">${esc(r.final_state||r.status)}</b></div></div><div class="fault-explain"><b>${esc(r.decision||'')}</b> · upstream_delta=${esc(r.upstream_delta??'n/a')} · ${esc(r.reconciliation||'')}<br>${esc(r.explanation||r.error||'')}</div>`;toast('Fault '+kind+': '+r.status)}catch(e){toast('Fault injection falhou: '+e.message)}};refresh();loadIntegration();