const $=s=>document.querySelector(s);let state=null,running=false;
async function api(path,opts={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...opts});if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function short(s,n=14){if(!s)return'—';return s.length>n?s.slice(0,n)+'…':s}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2400)}
function render(s){state=s;$('#mode').textContent=s.mode;$('#campaignId').textContent=s.campaign_id;$('#lastAction').textContent=s.last_action;const p=Math.round(s.step/s.total_steps*100);$('#stepText').textContent=`${s.step} / ${s.total_steps} eventos`;$('#progressPct').textContent=p+'%';$('#progressBar').style.width=p+'%';$('#riskValue').textContent=s.risk;const rl=s.risk>=80?'CRÍTICO':s.risk>=60?'ALTO':s.risk>=30?'ELEVADO':'NORMAL';$('#riskLabel').textContent=rl;$('#riskLabel').style.color=s.risk>=60?'var(--red)':s.risk>=30?'var(--amber)':'var(--green)';$('#signalCount').textContent=s.signals.length;$('#incidentState').textContent=s.incident?s.incident.state:'NÃO ABERTO';$('#incidentId').textContent=s.incident?s.incident.incident_id:'aguardando correlação';$('#upstreamHits').textContent=s.upstream_hits;$('#integrityState').textContent=s.verification.overall;$('#tamperState').textContent=s.tamper_status;$('#offlineState').textContent=s.offline_verify;renderIncident(s);renderPath(s);renderEvents(s);renderGraph(s);renderPolicy(s);renderIntegrity(s);renderQualification(s)}
function renderIncident(s){const i=s.incident,b=$('#incidentBadge');b.className='badge '+(i?'open':'neutral');b.textContent=i?'OPEN / HIGH':'CANDIDATE';$('#incidentSeverity').textContent=i?'Incidente correlacionado':'Sem incidente';$('#incidentSummary').textContent=i?i.summary:'Aguardando sinais suficientes.';$('#principal').textContent=i?i.principal:'—';$('#incidentStatus').textContent=i?i.state:'—';$('#incidentRisk').textContent=i?i.risk_score:s.risk;$('#policyTags').textContent=i?i.policy_tags.join(' · '):'—'}
function renderPath(s){const e=$('#attackPath');if(!s.events.length){e.innerHTML='<div class="empty" style="grid-column:1/-1">A campanha ainda não começou.</div>';return}e.innerHTML=s.events.slice(-12).map(x=>`<div class="attack-node ${x.severity.toLowerCase()} ${x.phase==='FASE 2'?'phase2node':''}"><div class="n-source">${esc(x.source)} · LSN ${x.lsn}</div><div class="n-title">${esc(x.summary)}</div><div class="n-meta">${esc(x.actor)} → ${esc(short(x.asset,24))}</div></div>`).join('')}
function renderEvents(s){const b=$('#eventRows');if(!s.events.length){b.innerHTML='<tr><td colspan="5" class="empty">Nenhum evento processado.</td></tr>';return}b.innerHTML=[...s.events].reverse().map(e=>`<tr><td>${e.lsn}</td><td><span class="evt-title">${esc(e.source)}</span><span class="evt-sub">${esc(e.phase)}</span></td><td><span class="evt-title">${esc(e.event_type)}</span><span class="evt-sub">${esc(e.summary)}</span></td><td><span class="evt-title">${esc(e.actor)}</span><span class="evt-sub">${esc(e.asset)}</span></td><td><span class="outcome ${esc(e.outcome)}">${esc(e.outcome)}</span><span class="evt-sub">${esc(e.reason_code||'')}</span></td></tr>`).join('')}
function renderGraph(s){const e=$('#graph'),nodes=s.graph.nodes||[],edges=s.graph.edges||[];$('#graphStats').textContent=`${nodes.length} nós / ${edges.length} arestas`;if(!nodes.length){e.innerHTML='<div class="empty graph-empty">O grafo surgirá conforme os sinais forem correlacionados.</div>';return}const W=620,H=355,v=nodes.slice(-24),ids=new Set(v.map(n=>n.id)),pos=new Map();v.forEach(n=>{const ring=n.kind==='incident'?0:n.kind==='event'?1:2,a=v.filter(x=>(x.kind==='incident'?0:x.kind==='event'?1:2)===ring),k=a.indexOf(n),r=ring===0?0:ring===1?95:145,ang=Math.PI*2*(k/Math.max(a.length,1))-Math.PI/2;pos.set(n.id,{x:W/2+Math.cos(ang)*r,y:H/2+Math.sin(ang)*r})});const lines=edges.filter(x=>ids.has(x.from)&&ids.has(x.to)).map(x=>{const a=pos.get(x.from),b=pos.get(x.to);return`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" class="graph-line"/>`}).join(''),colors={incident:'#ff5b66',event:'#43a5ff',actor:'#45d9d0',asset:'#a78bfa'},circles=v.map(n=>{const p=pos.get(n.id),r=n.kind==='incident'?20:n.kind==='event'?8:10;return`<g class="graph-node"><circle cx="${p.x}" cy="${p.y}" r="${r}" fill="${colors[n.kind]||'#6d87a1'}" stroke="#d7e9f9"/><text x="${p.x}" y="${p.y+r+13}" text-anchor="middle">${esc(short(n.label,18))}</text></g>`}).join('');e.innerHTML=`<svg viewBox="0 0 ${W} ${H}">${lines}${circles}</svg>`}
function renderPolicy(s){$('#compromisedCheck').textContent=s.incident?'SIM':'NÃO';$('#compromisedCheck').style.color=s.incident?'var(--red)':'var(--green)';const a=s.pending_approval,b=$('#approvalBox');b.innerHTML=a?`<span>HITL / ${esc(a.state)}</span><b>${esc(a.approval_id)} — ${esc(a.tool)}</b><small>${esc(a.principal)} → ${esc(a.target)} · single-use=${a.single_use}</small>`:'<span>HITL</span><b>Nenhuma aprovação pendente</b><small>Ações críticas podem exigir decisão humana.</small>'}
function renderIntegrity(s){$('#lastLsn').textContent=s.events.length?s.events.at(-1).lsn:0;$('#eventCount').textContent=s.events.length;$('#merkleRoot').textContent=s.merkle_root;$('#merkleShort').textContent='Merkle: '+short(s.merkle_root,18);$('#merkleState').textContent=s.verification.merkle;$('#chainVerify').textContent=s.verification.chain;$('#merkleVerify').textContent=s.verification.merkle}
function renderQualification(s){$('#qualification').innerHTML=s.qualification.map(x=>`<div class="qitem"><span>${esc(x.id)}</span><b><em>esperado ${esc(x.expected)}</em><strong class="${x.ok?'ok':'pending'}">${x.ok?esc(x.observed):'PENDING'}</strong></b></div>`).join('');const all=s.qualification.every(x=>x.ok),b=$('#qualificationBadge');b.textContent=all?'POC QUALIFIED':'EM EXECUÇÃO';b.style.color=all?'var(--green)':''}
async function refresh(){try{render(await api('/api/state'))}catch(e){toast('Falha ao ler estado: '+e.message)}}
$('#resetBtn').onclick=async()=>{render(await api('/api/reset',{method:'POST'}));toast('Ambiente reiniciado')};$('#stepBtn').onclick=async()=>render(await api('/api/step',{method:'POST'}));$('#runBtn').onclick=async()=>{if(running)return;running=true;$('#runBtn').textContent='Executando…';try{while(state&&!state.completed){render(await api('/api/step',{method:'POST'}));await new Promise(r=>setTimeout(r,420))}toast('Campanha completa executada')}finally{running=false;$('#runBtn').textContent='Executar campanha'}};
$('#tamperBtn').onclick=async()=>{const r=await api('/api/tamper-demo',{method:'POST'});$('#tamperResult').innerHTML=`Cópia sabotada: <b style="color:${r.verification.overall==='FAIL'?'var(--red)':'var(--green)'}">${r.verification.overall}</b> · chain=${r.verification.chain} · merkle=${r.verification.merkle}`;toast('Sabotagem controlada executada')};$('#exportBtn').onclick=async()=>{const r=await api('/api/export',{method:'POST'});$('#exportResult').innerHTML=`<b style="color:var(--green)">${r.status}</b> · ${esc(r.path)} · sha256 ${esc(short(r.sha256,20))}`;toast('Evidence Bundle gerado')};refresh();